spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173,http://localhost:5174,http://localhost:5175,http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: identity-service-route
          uri: lb://identity-service
          predicates:
            - Path=/auth/**
        - id: book-service-route
          uri: lb://book-service
          predicates:
            - Path=/books/**
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: lending-service-route
          uri: lb://lending-service
          predicates:
            - Path=/lending/**
        - id: reservation-service-route
          uri: lb://reservation-service
          predicates:
            - Path=/reservations/**

auth:
  jwt:
    secret: "scholario-secret-key-2026-very-secure"
